% 'fig5_new_base_600_101010.mat' and 'fig5_new_rob_600_101010.mat'were generated by 'fig5_main.mat'.
clc
clear all
close all

for snr_flag=1:15
    x(snr_flag)=0.8+snr_flag*0.2;
end

A=load('fig5_new_base_600_101010.mat');
B=load('fig5_new_rob_600_101010.mat');
sum_base = A.sum_base;
sum_rob  = B.sum_rob;
y1=sum_base/600;
y2=sum_rob/600;


offset_y=0.05;

yline(0.2, '--', 'Color', [0.5 0.5 0.5], 'LineWidth', 2);
hold on
yline(0.1, '--', 'Color', [0.5 0.5 0.5], 'LineWidth', 2);
hold on
h1=plot(x, y1, '-ob', 'LineWidth', 2, 'MarkerFaceColor', 'b')
hold on
for i = 1:15

    text(x(i), y1(i) + offset_y, num2str(y1(i), '%.2f'), ...
        'HorizontalAlignment', 'center', ... 
        'VerticalAlignment', 'bottom', ...  
        'FontSize', 10, ...
        'Color', 'b');                 
end
hold on
offset_y=-0.1;
h2=plot(x, y2, '-or', 'LineWidth', 2, 'MarkerFaceColor', 'r'); 
for i = 1:15
    text(x(i), y2(i) + offset_y, num2str(y2(i), '%.2f'), ...
        'HorizontalAlignment', 'center', ... 
        'VerticalAlignment', 'bottom', ...  
        'FontSize', 10, ...
        'Color', 'r');                       
end

hold on
ylim([-0.1 1.1])
legend([h1,h2],' Vertical Base Topology','Vertical Robustness Topology', 'FontSize', 12)
grid on
box on
ax = gca;
ax.FontSize = 12;
ax.XTick = 1:0.2:3.8;
xlabel('SNR', 'FontSize', 14, 'FontWeight', 'bold')
ylabel('Error Rate', 'FontSize', 14, 'FontWeight', 'bold')
title(['Comparison of Robustness under Two Methods' ],'FontSize',20,'FontWeight','bold')